Repository codenation-dev/squad-6-ad-nodejs-kroton-1, pull requests merged in 2020-03, with the labels that each got.

#20 Creating session controller
  src/app/controllers/SessionController.js
Labels: enhancement

#23 Feature/logs controller
  package-lock.json
  package.json
  src/app/controllers/ErrorController.js
  src/app/controllers/LogController.js
  src/app/models/Log.js
  src/app/syncDB.js
  src/routes.js
Labels: enhancement

#26 Controller for the user's endpoints
  src/app/controllers/UserController.js
  src/routes.js
Labels: enhancement

#27 Fix database connection error
  src/config/database.js
Labels: bug

#28 Replacing import/export for require
  src/app.js
  src/app/controllers/LogController.js
  src/app/controllers/SessionController.js
  src/app/controllers/UserController.js
  src/app/middlewares/auth.js
  src/app/models/Log.js
  src/app/models/User.js
  src/app/syncDB.js
  src/config/auth.js
  src/database/index.js
  src/routes.js
  src/server.js
  yarn.lock
Labels: enhancement

#34 Update Readme.md
  Readme.md
  src/swagger.json
Labels: documentation

#36 Update searchFilter
  src/app/utils/SearchHelper.js
Labels: enhancement

#47 Removing lockfiles
  docker-compose.yml
  npm-debug.log
  package-lock.json
  yarn.lock
Labels: enhancement
